---
- name: Create the exporter group
  group:
    name: "{{ _ga_exporter_system_group }}"
    state: present
    system: true
  when: _ga_exporter_system_group != "root"

- name: Create the exporter user
  user:
    name: "{{ _ga_exporter_system_user }}"
    groups: "{{ _ga_exporter_system_group }}"
    append: true
    shell: /bin/false
    system: true
    create_home: false
  when: _ga_exporter_system_user != "root"

- name: Create graylog-alert-exporter binary and config directory
  file:
    path: "{{ _ga_exporter_binary_install_dir }}"
    state: directory
    owner: "{{ _ga_exporter_system_user }}"
    group: "{{ _ga_exporter_system_group }}"
    mode: '0775'

- block:
    - name: Download graylog-alert-exporter archive to local tmp folder
      get_url:
        url: "{{ ga_exporter_url }}"
        dest: "/tmp/{{ ga_exporter_release_file }}"
        checksum: "sha256:{{ ga_exporter_checksum }}"
        mode: '0644'
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2

    - name: Create a directory for unpack archive
      file:
        path: "{{ _ga_exporter_tmp_path }}"
        state: directory
        mode: '0644'

    - name: Unpack graylog-alert-exporter archive
      unarchive:
        src: "/tmp/{{ ga_exporter_release_file }}"
        dest: "{{ _ga_exporter_tmp_path }}"
        remote_src: true
        creates: "{{ _ga_exporter_tmp_path }}/{{ ga_exporter_binary_name }}"
        mode: '0644'

    - name: Install graylog-alert-exporter binary
      copy:
        src: "{{ _ga_exporter_tmp_path }}/{{ ga_exporter_binary_name }}"
        dest: "{{ _ga_exporter_binary_install_dir }}/{{ ga_exporter_binary_name }}"
        remote_src: true
        mode: '0755'

  when: ga_exporter_binary_local_dir | length == 0

- name: Install graylog-alert-exporter binary from local
  copy:
    src: "{{ ga_exporter_binary_local_dir | regex_replace('\\/$', '') }}/{{ ga_exporter_binary_name | regex_replace('^\\/', '') }}"
    dest: "{{ _ga_exporter_binary_install_dir }}/{{ ga_exporter_binary_name }}"
    owner: "{{ _ga_exporter_system_user }}"
    group: "{{ _ga_exporter_system_group }}"
    mode: '0755'
  when: ga_exporter_binary_local_dir | length > 0
