---
- block:
    - name: Get latest release from github
      uri:
        url: "{{ ga_exporter_base_repo }}/releases/latest"
        method: GET
        status_code: 200
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set graylog-alert-exporter version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        ga_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"

  when:
    - ga_exporter_version == "latest"
    - ga_exporter_binary_local_dir | length == 0
  delegate_to: localhost
  run_once: true

- block:
    - name: "Get checksum for {{ go_arch }} architecture"
      set_fact:
        ga_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ ga_exporter_checksum }}"
      when:
        - "('Linux_' + go_arch + '.tar.gz') in item"

  delegate_to: localhost
  when: ga_exporter_binary_local_dir | length == 0
