---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # TODO: create test case for directories, files, user and permissions
    - name: Test exporter status
      block:
        - name: Get exporter status
          uri:
            url: "http://127.0.0.1:9889"
            method: GET
            status_code: 200
          register: _exporter_index
          until: _exporter_index.status == 200
          retries: 5
        - name: Assert that the exporter is running
          assert:
            that: "{{ _exporter_index.status == 200 }}"
    - name: Ensure file is existed
      block:
        - name: Set variable file paths
          set_fact:
            _binary_path: "/etc/exporter/graylog-alert-exporter/graylog-alert-exporter"
            _env_config_path: "/etc/default/alert-exporter"
        - name: Get binary existed
          stat:
            path: "{{ _binary_path }}"
          register: ga_binary_stat
        - name: Get default env existed
          stat:
            path: "{{ _env_config_path }}"
          register: ga_env_stat
        - name: Assert that exporter binary is existed
          assert:
            fail_msg: "Can't found binary in {{ _binary_path }}"
            that: 
              - ga_binary_stat.stat.exists
              - ga_binary_stat.stat.executable
        - name: Assert that default env file is existed
          assert:
            fail_msg: "Can't found default env in {{ _env_config_path }}"
            that:
              - ga_env_stat.stat.exists
              - ga_env_stat.stat.readable
